apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-nginx
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/jajera/kiro-eks-argocd-migration.git
    targetRevision: main
    path: apps/demo-nginx/base/manifests
  destination:
    name: in-cluster
    namespace: demo-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
