apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../infrastructure/gatekeeper/constraint-templates
  - ../../infrastructure/gatekeeper/constraints/containerlimits
  - ../../infrastructure/gatekeeper/constraints/requiredlabels
  - ../../infrastructure/gatekeeper/constraints/disallow-default-namespace
  - ../../infrastructure/gatekeeper/constraints/allow-privilege-escalation
  - ../../infrastructure/gatekeeper/constraints/networkpolicy-egress-defined
  - ../../infrastructure/gatekeeper/constraints/ingress-wafv2-public-alb
  - ../../infrastructure/gatekeeper/constraints/httpsonly
  - ../../infrastructure/gatekeeper/constraints/disallowedtags
  - ../../infrastructure/gatekeeper/constraints/block-nodeport-services
  - ../../infrastructure/gatekeeper/constraints/privileged-containers
  - ../../infrastructure/gatekeeper/constraints/host-namespaces
  - ../../infrastructure/gatekeeper/constraints/host-filesystem
  - ../../infrastructure/gatekeeper/constraints/disallowanonymous
  - ../../infrastructure/gatekeeper/constraints/verifydeprecatedapi
