apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-dev-eks-1
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/jajera/kiro-eks-argocd-migration.git
        revision: main
        directories:
          - path: apps/*/overlays/dev-eks-1
  template:
    metadata:
      name: "{{path.segments.[1]}}-dev-eks-1"
    spec:
      project: default
      source:
        repoURL: https://github.com/jajera/kiro-eks-argocd-migration.git
        targetRevision: main
        path: "{{path.path}}"
      destination:
        name: in-cluster
        namespace: "{{path.segments.[1]}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
